# Lab-1 : Attension

Before, I address what is self-attension ? first we review how RNN maintaining a hidden state allows to incorporate its representation of previous words/vectors it has processed with the current one it’s processing. Thus, Self attension is the method used by transformer for understanding the relevence of other words from vocabulary to the currect processing word in a given sentence.

### Task-0 

In [13]:
# python from scratch library
import math
import numpy as np 

# 
import torch
import torch.nn as nn 
import torch.nn.functional as F 


### Task-1

Attension - In a given sentence, It keep track every single word have some kind of affinity towards other word or not

$$ \text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V $$



In [5]:
# compute the query, key and value matrices
def softmax(x):
    return ( np.exp(x).T / np.sum(np.exp(x), axis=-1)).T

def scaled_dot_product_attention( q, k, v, mask=None): # mask is none by default and is in encoder setting which 
                                                       # can be changed to decoder by passing mask
    d_k=q.shape[-1]
    scaled= np.matmul(q, k.T)/math.sqrt(d_k)
    if mask is not None:
        scaled= scaled+mask
    print("scaled", scaled)
    attention= softmax(scaled)
    out=np.matmul(attention, v)
    return out, attention # new values , attention

In [8]:
# length of input sequence
L=4
# size of thes vectors
d_k = 8
d_v = 8
# initialize the q k v matrices
q = np.random.rand(L, d_k)
k = np.random.rand(L, d_k)
v = np.random.rand(L, d_v)

# compute the attention
out, attention = scaled_dot_product_attention(q, k, v)
# print the output and attention
print("Output:\n", out)
print("Attention:\n", attention)

# create a mask for the decoder - prediction of the future tokens
mask= np.tril(np.ones((L,L)))
mask[mask==0]=-np.inf
mask[mask==1]=0

# compute the attention with mask
out_masked, attention_masked = scaled_dot_product_attention(q, k, v, mask)
# print the output and attention with mask
print("Output with mask:\n", out_masked)
print("Attention with mask:\n", attention_masked)


scaled [[0.92437508 0.76109342 0.57632375 0.62003569]
 [0.90323288 0.74314335 0.46591913 0.53600242]
 [0.93105229 0.80788533 0.59086872 0.60714951]
 [0.67256557 0.58922815 0.40639233 0.41051461]]
Output:
 [[0.58980873 0.65315452 0.58977675 0.75164092 0.60384918 0.42990405
  0.47024889 0.76868091]
 [0.58973423 0.65413257 0.59438378 0.74689309 0.60508062 0.43462382
  0.47582019 0.76445329]
 [0.59206776 0.6592164  0.59325714 0.74994701 0.60851148 0.42665397
  0.47231488 0.76395251]
 [0.5953361  0.66124875 0.59208973 0.75184169 0.6111631  0.41866359
  0.46786183 0.76384738]]
Attention:
 [[0.30367215 0.25792453 0.21441156 0.22399176]
 [0.31343185 0.26706509 0.2024045  0.21709857]
 [0.30128865 0.26637413 0.21440895 0.21792827]
 [0.28936702 0.26622942 0.22174379 0.22265977]]
scaled [[0.92437508       -inf       -inf       -inf]
 [0.90323288 0.74314335       -inf       -inf]
 [0.93105229 0.80788533 0.59086872       -inf]
 [0.67256557 0.58922815 0.40639233 0.41051461]]
Output with mask:
 [[0.31

### Task-2 : Multi-Head Attension

In [17]:
def scaled_dot_product(q, k, v, mask=None):
    d_k = q.size()[-1]
    scaled = torch.matmul(q, k.transpose(-1, -2)) / math.sqrt(d_k)
    if mask is not None:
        scaled += mask
    attention = F.softmax(scaled, dim=-1)
    values = torch.matmul(attention, v)
    return values, attention

In [18]:
sequence_length = 4 # My name is Ankit
batch_size = 1 # number of sentences in batch
input_dim = 512 # vector dimension of each input
d_model = 512 # vector dimension of each output  of each attention unit       
x = torch.rand((batch_size, sequence_length, input_dim)) # input tensor

qkv_layer = nn.Linear(input_dim, 3*d_model) # here we are concatenating q, k, v in one matrix which will be split later
qkv = qkv_layer(x)

num_heads= 8 # now we have 8 attention head
head_dim= d_model//num_heads # each head will have dim of 512 / 8 => 64
qkv = qkv.reshape(batch_size, sequence_length, num_heads, 3*head_dim)

# let's change sequencing in qkv just to make things easy in future and perform parallel operations of last 2 dimensions
qkv=qkv.permute(0, 2, 1, 3) # [batch_size, num_heads, sequence_length, 3*head_dim]
qkv.shape

# now we will divide the chuck of each head into q, k, v
q, k, v=qkv.chunk(3, dim=-1) # divide last dimension by 3 i.e 192/3 = 64

values, attention = scaled_dot_product(q, k, v, mask=mask)


RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [20]:

class MultiHeadAttention(nn.Module):

    def __init__(self, input_dim, d_model, num_heads):
        super().__init__()
        self.input_dim = input_dim
        self.d_model = d_model
        self.num_heads = num_heads
        self.head_dim = d_model // num_heads
        self.qkv_layer = nn.Linear(input_dim , 3 * d_model)
        self.linear_layer = nn.Linear(d_model, d_model)
    
    def forward(self, x, mask=None): # forward pass
        
        batch_size, sequence_length, input_dim = x.size()
        print(f"x.size(): {x.size()}\n")
        print("-"*50)

        qkv = self.qkv_layer(x)
        print(f"qkv.size(): {qkv.size()}\n")
        print("-"*50)

        qkv = qkv.reshape(batch_size, sequence_length, self.num_heads, 3 * self.head_dim)
        print(f"qkv.size(): {qkv.size()}")
        qkv = qkv.permute(0, 2, 1, 3)
        print(f"qkv.size(): {qkv.size()}\n")
        print("-"*50)

        q, k, v = qkv.chunk(3, dim=-1)
        print(f"q size: {q.size()}     k size: {k.size()}     v size: {v.size()}\n")
        print("-"*50)

        values, attention = scaled_dot_product(q, k, v, mask)
        print(f"values.size(): {values.size()}          attention.size:{ attention.size()} ")
        print("-"*50)
        values = values.reshape(batch_size, sequence_length, self.num_heads * self.head_dim)
        print(f"values.size(): {values.size()}\n")
        print("-"*50)

        out = self.linear_layer(values)
        print(f"out.size(): {out.size()}\n")
        print("-"*50)
        return out

In [21]:
input_dim = 512
d_model = 512
num_heads = 8

batch_size = 30
sequence_length = 5
x = torch.randn( (batch_size, sequence_length, input_dim) )

model = MultiHeadAttention(input_dim, d_model, num_heads)
out = model.forward(x)

x.size(): torch.Size([30, 5, 512])

--------------------------------------------------
qkv.size(): torch.Size([30, 5, 1536])

--------------------------------------------------
qkv.size(): torch.Size([30, 5, 8, 192])
qkv.size(): torch.Size([30, 8, 5, 192])

--------------------------------------------------
q size: torch.Size([30, 8, 5, 64])     k size: torch.Size([30, 8, 5, 64])     v size: torch.Size([30, 8, 5, 64])

--------------------------------------------------
values.size(): torch.Size([30, 8, 5, 64])          attention.size:torch.Size([30, 8, 5, 5]) 
--------------------------------------------------
values.size(): torch.Size([30, 5, 512])

--------------------------------------------------
out.size(): torch.Size([30, 5, 512])

--------------------------------------------------


## Reference 
1. https://colab.research.google.com/github/tensorflow/tensor2tensor/blob/master/tensor2tensor/notebooks/hello_t2t.ipynb
2. 